// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import UpdateQuantityrController from "./cart/update_quantity_controller"
application.register("update-quantity", UpdateQuantityrController)

import DiscountRangeSliderController from "./cart/discount_range_slider_controller"
application.register("discount-range-slider", DiscountRangeSliderController)